### ISSUE TITLE
pictures

### ISSUE THREAD

**Issue by RalfHei** [karljame/project2#3]
Put all the pictures do a folder in github

**Comment by KaroliinaPilden** [comment]
brian may https://i.pinimg.com/236x/82/6e/71/826e71a6df756ae282b24a36d7494984.jpg

**Comment by KaroliinaPilden** [comment]
john deacon https://www.fullthrottlerock.net/John%20Deacon%20301018.jpg

**Comment by KaroliinaPilden** [comment]
Queen: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f_R2LS6U/SharedImage-53599.jpg?t=071233d688c9ddd18b24
Queen II: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f3noMS6U/SharedImage-53612.jpg?t=1a8ff15292f3d96da274
Sheer Heart Attack: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fM84LS6U/SharedImage-53600.jpg?t=2965822e366a332edbf4
A Night At The Opera: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f3C7LS6U/SharedImage-53601.jpg?t=96658919e620ce1dee51
A Day At The Opera: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fAb9LS6U/SharedImage-53602.jpg?t=1afaad5e759e53db1e05
News Of The World: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f10_LS6U/SharedImage-53603.jpg?t=028a5528c4b1edfbc2cc
Jazz: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fdcCMS6U/SharedImage-53604.jpg?t=efbe08dbd4e46ac03bce
The Game: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f0vEMS6U/SharedImage-53605.jpg?t=ff1f84234d506391aa6d
Flash Gordon: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fJ0GMS6U/SharedImage-53606.jpg?t=6c07175dae40011f5062
Hot Space: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f2JJMS6U/SharedImage-53607.jpg?t=43be0e48c3f160532374
The Works: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.f9jLMS6U/SharedImage-53608.jpg?t=d9d45ddac42ba511a040
A Kind Of Magic: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fVtNMS6U/SharedImage-53609.jpg?t=fcd8bf4804e05c857139
The Miracle: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fhChMS6U/SharedImage-53610.jpg?t=14ff137c508f1a9fcfe0
Innuendo: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.fLTkMS6U/SharedImage-53611.jpg?t=f442e3904a7375ca0b99
Made In Heaven: https://dvfnvgxhycwzf.cloudfront.net/media/SharedImage/imageFull/.feCsMS6U/SharedImage-53613.jpg?t=3aa2c5bfcf3b8286a822
