### ISSUE TITLE
information about band members

### ISSUE THREAD

**Issue by RalfHei** [karljame/project2#4]
Find information about the band members of queen

**Comment by ErkkiTa** [comment]
**Freddie Mercury**

Freddie Mercury (1946-1991) was a British singer, songwriter, record producer, and lead vocalist of the rock band Queen. Regarded as one of the greatest lead singers in the history of rock music. 

**Brian Harold May**

Brian Harold May (1947) is an English musician, singer, songwriter and astrophysicist. He is the lead guitarist of the rock band Queen. May was a co-founder of Queen with lead singer Freddie Mercury and drummer Roger Taylor.

**Roger Meddows Taylor**

Roger Meddows Taylor (1949) is an English musician, singer, songwriter, and multi-instrumentalist, best known as the drummer for the rock band Queen. As a drummer, Taylor was recognised early in his career for his unique sound. He was voted by radio listeners as the eighth-greatest drummer in classic rock music history in a poll conducted by Planet Rock in 2005.

**John Richard Deacon**

John Richard Deacon (1951) is an English retired musician, best known for being the bass guitarist for the rock band Queen. He composed several songs for the group—including Top 10 hits "You're My Best Friend", "Another One Bites the Dust", "Back Chat", and "I Want to Break Free"—and was involved in the band's financial management.
